# Generated by Django 3.0.8 on 2020-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='steps',
            field=models.TextField(default='Steps'),
            preserve_default=False,
        ),
    ]
