# Generated by Django 3.1.7 on 2021-03-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_auto_20210314_0435'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(name__length__gt=0), name='ingredient_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name',), name='ingredient_name_unique'),
        ),
    ]
