# Generated by Django 3.1.7 on 2021-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_auto_20210317_0818'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cocktail',
            constraint=models.CheckConstraint(check=models.Q(name__length__gt=0), name='cocktail_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='cocktail',
            constraint=models.UniqueConstraint(fields=('name',), name='cocktail_name_unique'),
        ),
    ]
