# Generated by Django 3.1.7 on 2021-03-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_auto_20210317_0822'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(quantity__gt=0), name='quantity_gt_0'),
        ),
    ]
