name: Django CI/CD Workflow

# triggers for the workflow
on:
  push:
    branches:
      - master

# job definitions
jobs:
  package-job: # package job for building and publishing docker image
    runs-on: self-hosted
    steps:
      - name: Checkout Code # checking out code.
        uses: actions/checkout@v2
      - name: Define version
        run: cat version.txt >> $GITHUB_ENV
      - name: Build & Publish Image
        uses: docker/build-push-action@v1
        with:
          tags: stable,${{ env.COCKTAIL_MASTER_VERSION }}
          push: false
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Package-job in ${{ github.repository }} finished

  deploy-job: # deploy job
    runs-on: self-hosted
    needs: [package-job] # will require package-job to be successful for triggering
    steps:
      - name: Docker compose
        run: docker-compose up -d
        env:
          DB_ENGINE: django.db.backends.postgresql_psycopg2
          DB_HOST: postgres
          DB_PORT: 5432
          DB_NAME: cocktail_master
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
          PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Deploy-job in ${{ github.repository }} finished
